version: '3.3'

services:
      
  password-api:
    ports:
      - "5001:5001"

  password-web:
    ports:
      - "8085:80"
    environment:
      - "PasswordApi:Url=http://password-api:5001"
    depends_on:
      - password-api

networks:
  password-net: