version: '3.3'

services:
      
  elasticsearch:
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.platform.os == linux
        - node.role == worker
    
  kibana:
    deploy:
      placement:
        constraints:
        - node.platform.os == linux
        - node.role == worker

networks:
  analytics-net:
    external:
      name: shared-analytics-network
  dmz-net:
    external:
      name: shared-dmz-network