version: '3.3'

services:
      
  elasticsearch:
    image: elasticsearch:5.6-alpine
    networks:
      - analytics-net
      
  kibana:
    image: kibana:5.6
    networks:
      - analytics-net
      - dmz-net

networks:
  analytics-net:
  dmz-net: